### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by wazabees** [steven-murray/beet-summarize#6]
beets version
```
beets version 1.5.0
Python version 3.8.5
plugins: copyartifacts, edit, fetchart, importadded, importfeeds, info, inline, mbcollection, mbsync, mpdstats, mpdupdate, originquery, scrub, smartplaylist, zero
```

Any idea what this error is? I installed summarize via `pip install git+git://github.com/steven-murray/beet-summarize.git`
```
** error loading plugin summarize:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/beets/plugins.py", line 275, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.summarize'

error: unknown command 'summarize'
```

**Comment by steven-murray** [comment]
Looks like it wasn't installed properly? Is your `pip` in a different Python env from `beets` perhaps?

**Comment by wazabees** [comment]
Hello, and thanks for for getting back to me!
It looks like they're installed in the same place.

`beet: /home/user/.local/bin/beet`
`pip: /home/user/.local/bin/pip3.8 /home/user/.local/bin/pip`

I tried running the command again and got:

`pip install git+git://github.com/steven-murray/beet-summarize.git`
```
Defaulting to user installation because normal site-packages is not writeable
Collecting git+git://github.com/steven-murray/beet-summarize.git
  Cloning git://github.com/steven-murray/beet-summarize.git to /tmp/pip-req-build-b28xavzs
Requirement already satisfied (use --upgrade to upgrade): summarize==0.1.0 from git+git://github.com/steven-murray/beet-summarize.git in /home/user/.local/lib/python3.8/site-packages
Building wheels for collected packages: summarize
  Building wheel for summarize (setup.py) ... done
  Created wheel for summarize: filename=summarize-0.1.0-py3-none-any.whl size=9147 sha256=b49188383a609b812ba6caba24be3506012d78edd1e37e2a6bfa3e783e34831c
  Stored in directory: /tmp/pip-ephem-wheel-cache-xjyq5ohb/wheels/9f/65/10/df9c14f9cdb91439ac5878d7d98a24f2a1546e3c7513f5ffdd
Successfully built summarize
```

`beet summarize`
```
/home/user/.local/lib/python3.8/site-packages/beets/mediafile.py:21: UserWarning: beets.mediafile is deprecated; use mediafile instead
  warnings.warn("beets.mediafile is deprecated; use mediafile instead")
** error loading plugin summarize:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/beets/plugins.py", line 275, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.summarize'

error: unknown command 'summarize'
```

**Comment by steven-murray** [comment]
OK, thanks for the update! Looks like this must be a bug. I don't get to work on this much, so I might be a while coming up with a solution -- but I will try!

**Comment by catap** [comment]
@steven-murray to fix this issue you must move `summarize` to `beetsplug` directory and update `setup.py` ;)

**Comment by steven-murray** [comment]
Hi @wazabees and @catap does 59d68b3c8ebbf6740bc2fc4fa4cac72d678c3586 fix the issue?

**Comment by catap** [comment]
@steven-murray I can't build it anymore :(
```
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 setup.py --no-user-cfg build -j12 
Traceback (most recent call last):
  File "/opt/local/var/macports/build/_Users_catap_src_macports-ports_audio_beets/beets-summarize/work/steven-murray-beet-summarize-59d68b3/setup.py", line 60, in <module>
    version=find_version(),
  File "/opt/local/var/macports/build/_Users_catap_src_macports-ports_audio_beets/beets-summarize/work/steven-murray-beet-summarize-59d68b3/setup.py", line 13, in find_version
    with open(os.path.join(os.path.dirname(__file__), "summarize", "__init__.py")) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/local/var/macports/build/_Users_catap_src_macports-ports_audio_beets/beets-summarize/work/steven-murray-beet-summarize-59d68b3/summarize/__init__.py'
```

**Comment by wazabees** [comment]
@steven-murray - I got a different error message, as below.

```
Collecting git+git://github.com/steven-murray/beet-summarize.git
  Cloning git://github.com/steven-murray/beet-summarize.git to /tmp/pip-req-build-8t6nt_la
  Running command git clone -q git://github.com/steven-murray/beet-summarize.git /tmp/pip-req-build-8t6nt_la
  Resolved git://github.com/steven-murray/beet-summarize.git to commit 59d68b3c8ebbf6740bc2fc4fa4cac72d678c3586
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8t6nt_la/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8t6nt_la/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-exvjjgh_
         cwd: /tmp/pip-req-build-8t6nt_la/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-8t6nt_la/setup.py", line 60, in <module>
        version=find_version(),
      File "/tmp/pip-req-build-8t6nt_la/setup.py", line 13, in find_version
        with open(os.path.join(os.path.dirname(__file__), "summarize", "__init__.py")) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-8t6nt_la/summarize/__init__.py'
    ----------------------------------------
WARNING: Discarding git+git://github.com/steven-murray/beet-summarize.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by catap** [comment]
@wazabees why it is different? It is the same message ;)

**Comment by wazabees** [comment]
> @wazabees why it is different? It is the same message ;)

You're right! Sorry, I misread :)

**Comment by steven-murray** [comment]
Ah. OK I think the documentation for writing beets plugins has been updated since I wrote this plugin. Looking at the new documentation, I made some updates, adding relevant code to the `__init__.py` to ensure the plugin goes into the namespace. Can you retest?

**Comment by catap** [comment]
@steven-murray ea4d8656d09ab96bd94f48b506c32d189365b150 works on my side.

Thanks!

**Comment by catap** [comment]
FYI: I'm making beets port for MacPorts https://github.com/macports/macports-ports/pull/12132 and it includes this plugin ;)

**Comment by steven-murray** [comment]
@catap thanks! That's really cool. Let me know if I can help with anything else -- like I said above, I don't get a chance to work on this much (if at all), but bugfixes and stuff are obviously important :-)
