### ISSUE TITLE
Plugin crashed without arguments

### ISSUE THREAD

**Issue by catap** [steven-murray/beet-summarize#7]
```
√ Music % beet summarize         
Traceback (most recent call last):
  File "/opt/local/bin/beet", line 33, in <module>
    sys.exit(load_entry_point('beets==1.5.0', 'console_scripts', 'beet')())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/ui/__init__.py", line 1291, in main
    _raw_main(args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/ui/__init__.py", line 1278, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beetsplug/summarize.py", line 230, in summarize
    show_summary(lib, decargs(args), opts.group_by, opts.stats, not opts.not_reverse)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beetsplug/summarize.py", line 212, in show_summary
    sort_stat = stats.keys()[0]
TypeError: 'odict_keys' object is not subscriptable
? Music % beet
```

**Comment by catap** [comment]
And it seems broken :(
```
√ Music % beet help summarize -g year -R 
Usage: beet help [options]

beet help: error: no such option: -g
? Music % beet help summarize --group-by year -R
Usage: beet help [options]

beet help: error: no such option: --group-by
? Music % 
```

**Comment by steven-murray** [comment]
Dang. I'll have to re-read the plugin dev documentation. I'll try to do this soon.

**Comment by steven-murray** [comment]
I think I fixed the first issue (about ordered dicts). The second issue seems more to do with how CLI arguments are detected by beets, and may be a version issue. It'll take me a little more time to fix that

**Comment by steven-murray** [comment]
Looking at this again, I think doing `beet help summarize` should work, but `beet help summarize -g year` won't work because `help` doesn't know about the `-g` option.
